server:
  port: 8081
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-consumer.log
spring:
  kafka:
    bootstrap-servers: 172.31.8.239:9092
    consumer:
      client-id: stormeye-kafka-dev