services:
  kafka:
    server: ${KAFKA_BOOTSTRAP_SERVER:localhost}
    port: ${KAFKA_BOOTSTRAP_PORT:9092}
    client: ${KAFKA_CLIENT_ID:stormeye-kafka}
    topics:
      - DeployProcessed
      - BlockAdded
      - DeployAccepted
      - FinalitySignature
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
server:
  port: 8083
spring:
  output:
    ansi:
      enabled: ALWAYS # force pretty output!
  application:
    name: Casper Event Store Kafka Consumer

