server:
  port: 8083
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: ${HOME}/cspr-consumer.log
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: stormeye-kafka-local